### PR TITLE
Splice prose into core/exec/instructions.rst with todos

### PR DESCRIPTION
**Pull request by jaehyun1ee**
This PR splices the execution prose of Wasm instructions into the spec document, document/core/exec/instructions.rst. They fall into three categories,

**[1] Spliced without any todos**

Generated prose that are either:
1. _same_ as the actual, handwritten prose, or
2. differs from the actual prose, yet _in trivial agreement_ with the spliced formal rules

are simply spliced into the document, as expected.

**[2] Spliced with a todo list**

Multiple generated prose differs in the English expressions they use from the actual prose, varying in degree. I have listed `.. todo::` for each prose, spliced the generated prose, and also left the actual prose there for comparision.

Enumerating the todos, which is almost the same as mentioned in this [doc](https://docs.google.com/document/d/1sdktCCAOfiB0dk52keEXAE7NFPDUH2BXHw0oBqsLj7s/edit?usp=sharing),

1. Remove trailing "Do nothing."
2. SpecTec currently defines the image of numeric functions as a sequence, not a set.
3. Introduce if-let instruction instead of "is of the case".
4. Guarantees from validation can help simplify the prose.
5. Use "the expansion of" instead of `$expand` function application.
6. Maybe we want to be more precise than just saying "Either" in the prose, elaborating that it may succeed or fail non-deterministically.
7. Render various `$inverse_of_` with display hint.
8. PR#90 working on "Enter ..." prose.
9. Need to handle `RulePr` `s |- ref : rt` properly in prose instead of `$ref_type_of`.
10. If the "current context is ..." needs to be handled, either by SpecTec or manually, mentioned in PR#90.
11. AL's rendered `ref.cast (ref (null ()) y)` is broken. Need to handle TERMINAL? case in AL-to-EL-expr phase.

**[3] Not spliced**

Some are _not_ spliced because:
1. pdflatex on the generated tex fails to render deeply nested prose (`RETURN_CALL_REF`).
2. Some vector instructions seem to be WIP (`VRELOP`, ...).
3. Not sure where to splice `CALL_REF`: either in `CALL_REF` or `<exec-invoke>`?

### CODE REVIEW

**Review by rossberg — APPROVED** [review]
Excellent, looks good to me!

> 6. Maybe we want to be more precise than just saying "Either" in the prose, elaborating that it may succeed or fail non-deterministically.

That's probably something that's best expressed in a note.

> 1. pdflatex on the generated tex fails to render deeply nested prose (`RETURN_CALL_REF`).

Oh wow, how deep is it nested?

> 2. Some vector instructions seem to be WIP (`VRELOP`, ...).

It's fine to add the prose for those as well, the WIP on my end is mostly tweaking the rendering.

> 3. Not sure where to splice `CALL_REF`: either in `CALL_REF` or `<exec-invoke>`?

Yeah, I've bumped my head against that as well. My conclusion so far was to have it at exec-invoke, but that may not be perfect either.

**Comment by jaehyun1ee** [comment]
> 1. pdflatex on the generated tex fails to render deeply nested prose (RETURN_CALL_REF).
> > Oh wow, how deep is it nested?

It has 5 levels of enumeration. One hack can be using the [enumitem package](https://github.com/Wasm-DSL/spectec/blob/5d34c4aac4878eff7c5051c3079fc0186a0fdadb/spectec/test-prose/doc/conf.py#L44-L55), which I have used to splice prose into `test-prose/doc`.

```
execution_of_RETURN_CALL_REF yy
1. Let z be the current state.
2. Pop all values val* from the top of the stack.
3. If a label is now on the top of the stack, then:
  a. Pop the current label from the stack.
  b. Push the values val* to the stack.
  c. Execute the instruction (RETURN_CALL_REF yy).
4. Else if a frame is now on the top of the stack, then:
  a. Pop the current frame from the stack.
  b. Let admin_u1* ++ admin_u0 be val*.
  c. If admin_u0 is of the case REF.FUNC_ADDR, then:
    1) Let (REF.FUNC_ADDR a) be admin_u0.
    2) If (a < |$funcinst(z)|), then:
      a) Assert: Due to validation, $expanddt($funcinst(z)[a].TYPE) is of the case FUNC.
      b) Let (FUNC y_0) be $expanddt($funcinst(z)[a].TYPE).
      c) Let (t_1^n -> t_2^m) be y_0.
      d) If (|admin_u1*| ≥ n), then:
        1. Let val'* ++ val^n be admin_u1*.
        2. Push the values val^n to the stack.
        3. Push the value (REF.FUNC_ADDR a) to the stack.
        4. Execute the instruction (CALL_REF yy).
  d. If admin_u0 is of the case REF.NULL, then:
    1) Trap.
```

> 2. Some vector instructions seem to be WIP (VRELOP, ...).
> > It's fine to add the prose for those as well, the WIP on my end is mostly tweaking the rendering.

I see, I have inserted the splice anchors for SIMD prose.

> 3. Not sure where to splice CALL_REF: either in CALL_REF or <exec-invoke>?
> > Yeah, I've bumped my head against that as well. My conclusion so far was to have it at exec-invoke, but that may not be perfect either.

One problem is that we have merged the two rules, `call_ref-func` and `call_ref-null` into one prose algorithm for `CALL_REF`. So I am not sure where to splice the prose between the two, or maybe in both?

**Comment by rossberg** [comment]
> It has 5 levels of enumeration.

Ah, but looking at the prose, the deep nesting is a consequence of "accidental" conditionals: steps 4, 4c2, 4c2d, and 4d should eventually all be assertions, not conditions. In particular, that would make the nesting for 4c2 and 4c2d disappear, flattening the innermost three levels.

> I see, I have inserted the splice anchors for SIMD prose.

Cool, thanks!

> One problem is that we have merged the two rules, `call_ref-func` and `call_ref-null` into one prose algorithm for `CALL_REF`. So I am not sure where to splice the prose between the two, or maybe in both?

Yeah, I'll move the call_ref-null over to match this up. And mull over how to structure it best some more.

**Review by rossberg — APPROVED** [review]

**Comment by jaehyun1ee** [comment]
> Ah, but looking at the prose, the deep nesting is a consequence of "accidental" conditionals: steps 4, 4c2, 4c2d, and 4d should eventually all be assertions, not conditions.

Indeed, we'll need to address this issue of properly inserting assertions instead of conditions later. I'll leave it as a todo in the spliced document for now.

**Pull request merged**
