### PR TITLE
Il-to-IL pass: Animate

### PR DESCRIPTION
**Pull request by f52985**
Il-to-IL pass: Animate

This transformation will
1) make the equality conditions explicit as assignment conditions, if they are indeed assignments, and
2) reorder the premises that resembles the actual order of execution in interpreter

~Depends upon #9.~
Depends upon #13

### CODE REVIEW

**Comment by nomeata** [comment]
So this changes
```
    -- if ($binop(binop, nt, c_1, c_2) = [c])
```
to
```
    -- where [c] := $binop(binop, nt, c_1, c_2)
```

Nice!

Even more reason to improve the sidecondition pass to do the more advanced thing and rewrite !(e) to a fresh variable x and add a premise of the form e=?x, which this pass then can pick up!

---

Is there a semantic difference between `if` and `where`? Is there an implicit assumption that, due to validation, the pattern match in the `where` assignment will not fail?

Relatedly, `$binop` doesn’t have definitions yet, only this declaration:
```
def $binop(binop_numtype, numtype, c, c) : c_numtype*
```
It seems it returns no result when undefined (division by zero for example?)

Does it ever return more than one result? If not, why not
```
def $binop(binop_numtype, numtype, c, c) : c_numtype?
```

**Comment by f52985** [comment]
> Is there a semantic difference between if and where? Is there an implicit assumption that, due to validation, the pattern match in the where assignment will not fail?

I expect them to have exact same meanings in terms of semantics.
(Let's say, `where` is hint for imperative backeds (prose, interpreter, ...))

>It seems it returns no result when undefined (division by zero for example?)
Does it ever return more than one result? If not, why not `def $binop(binop_numtype, numtype, c, c) : c_numtype?`

That looks great! (Although I cannot confirm if it's really the case that more than one values never can be returned.)

**Comment by nomeata** [comment]
I wrote a pass for the option thingy in https://github.com/Wasm-DSL/spectec/pull/13. No need to pull this here yet, or anything, but it may be good to know that there will be more equations to be anmiated  :-)

**Comment by f52985** [comment]
Without any changes, the equation containing option:
```
-- if ($size(nt <: valtype) = ?(o0))
```
is already animated as:
```
-- where ?(o0) := $size(nt <: valtype)
```
which is great!

**Comment by rossberg** [comment]
Both unops and binops can have multiple possible results, due to NaN non-determinism. In other words, they are set-valued functions. We are not modelling that accurately yet. We'll probably need to add some set-related expressions to the DSL for that purpose.

**Comment by nomeata** [comment]
Should we model them as relations then, rather than as functions?

**Comment by rossberg** [comment]
Notationally it's preferable to say `c ∈ binop(c1,c2)`, like in the actual spec. I believe we will need sets anyway, so this should be okay.

**Comment by f52985** [comment]
I'll reopen this pull request due to conflicts

**Pull request closed without merging**
