### PR TITLE
Merge/spec exception handling

### PR DESCRIPTION
**Pull request by rossberg**
Hi folks, it looks like I need help again. This PR merges the now phase-4 exceptions proposal into SpecTec. The PR includes the full SpecTec formalisation for that as well, and adapts the interpreter backend accordingly.

Unfortunately, I'm still running into strange issues. I get the following error from the interpreter on sample.wat:
```
The key 'aa' is not in the map: 
{aa_I: [],
  byte: [],
  da: [],
  data: [],
  datamode: [],
  dt: [(DEF (REC [(SUB (FINAL ?()) [] (FUNC ([I32, I32], [I32])))]) 0x0)],
  ea: [],
  elem: [],
  elemmode: [],
  elemtype: [],
  export: [(EXPORT addTwo (FUNC 0x0))],
  expr_E: [],
  expr_F: [[(LOCAL.GET 0x0), (LOCAL.GET 0x1), (BINOP I32 ADD)]],
  expr_G: [],
  expr_T: [],
  externval: [],
  fa: [0x7],
  fa_I: [],
  func: [(FUNC 0x0 [] [(LOCAL.GET 0x0), (LOCAL.GET 0x1), (BINOP I32 ADD)])],
  ga: [],
  ga_I: [],
  global: [],
  globaltype: [],
  import: [],
  local: [[]],
  ma: [],
  ma_I: [],
  mem: [],
  memtype: [],
  module: (MODULE [(TYPE (REC [(SUB (FINAL ?()) [] (FUNC ([I32, I32], [I32])))]))] [] [(FUNC 0x0 [] [(LOCAL.GET 0x0), (LOCAL.GET 0x1), (BINOP I32 ADD)])] [] [] [] [] [] [] ?() [(EXPORT addTwo (FUNC 0x0))]),
  ref_E: [],
  ref_T: [],
  start: ?(),
  ta: [],
  ta_I: [],
  table: [],
  tabletype: [],
  tag: [],
  type: [(TYPE (REC [(SUB (FINAL ?()) [] (FUNC ([I32, I32], [I32])))]))],
  val_G: [],
  x: [0x0]
}.
Not_found
```
It doesn't give me any source location, but extrapolating from the environment this must be in the [$allocmodule](https://github.com/Wasm-DSL/spectec/blob/d48abfd7a21701d11fb919202a3871a0b211cca0/spectec/spec/wasm-3.0/9-module.watsup#L104) function. Somehow it does not have the local variable `aa`, although it exists in the definition.

Could somebody perhaps help and tell me what I'm doing wrong? And ideally, improve the error message? :)

### CODE REVIEW

**Comment by f52985** [comment]
In fact, this is not an interpreter error, but instead, a failed prose generation.

Here is a generated prose for the function $allocmodule:
```
allocmodule module externval* val_G* ref_T* ref_E**
...
8. Let fa* be (|s.FUNCS| + i_F)^(i_F<|func*|).
9. Let ga* be (|s.GLOBALS| + i_G)^(i_G<|global*|).
10. Let ta* be (|s.TABLES| + i_T)^(i_T<|table*|).
11. Let ma* be (|s.MEMS| + i_M)^(i_M<|mem*|).
12. Let ea* be (|s.ELEMS| + i_E)^(i_E<|elem*|).
13. Let da* be (|s.DATAS| + i_D)^(i_D<|data*|).
...
28. Let xi* be $allocexports({ TYPES: []; FUNCS: fa_I* ++ fa*; GLOBALS: ga_I* ++ ga*; TABLES: ta_I* ++ ta*; MEMS: ma_I* ++ ma*; TAGS: aa_I* ++ aa*; ELEMS: []; DATAS: []; EXPORTS: []; }, export*).
...
```

In the generated prose, the variable `aa*`, unlike other addresses, is used on line 28 without definition.

This wrong prose is due to the cyclic definition in the original rule:
```
  -- if (s_1, fa*) = $allocfuncs(s, dt*[x]*, (FUNC x local* expr_F)*, moduleinst^(|func*|))
  -- if (s_2, ga*) = $allocglobals(s_1, globaltype*, val_G*)
  -- if (s_3, ta*) = $alloctables(s_2, tabletype*, ref_T*)
  -- if (s_4, ma*) = $allocmems(s_3, memtype*)
  -- if (s_5, aa*) = $alloctags(s_4, dt*[y]*)
  ...
  -- if moduleinst = {
      TYPES dt*,
      FUNCS fa_I* fa*, \
      GLOBALS ga_I* ga*,
      TABLES ta_I* ta*, \
      MEMS ma_I* ma*,
      TAGS aa_I* aa*,
      ELEMS ea*, \
      DATAS da*,
      EXPORTS xi*
    }
```

In order to compute the variable `aa`, it requires to compute the sequence of stores `s_4`, `s_3`, ..., `s_1`,
and computing the variable `s_1` which requires the variable `moduleinst`.
But again, computing the variable `moduleinst` requires the variable `aa`, resulting in the cyclic definition and wrong prose.

In order to break this cycles, forward guesses are used for other addresses as in
`  -- if fa* = ($(|s.FUNCS|+i_F))^(i_F<|func*|)`
I made commit that adds a forward guess for `aa` as well, resulting in the correct prose for now,
which removes the error message above.
(Unfortunately, it seems that other interpreter-error is appearing though..)

* Regarding error message:
Yes, improving the error message in case of `Not_found` from the interpreter to include the source location, should be done.
In addition to that, considering that the root cause of the problem lies in the translation into prose,
I think appropriate error message might be required that indicates a cyclic definition from the original rule.

**Comment by rossberg** [comment]
Ah, I see! Thanks for debugging this!

I'll create an issue for the error reporting.

The remaining interpreter error probably has to do with the divergence between 1.0/2.0 vs 3.0 module structure. The conversion will likely need a version flag. I can try to do that.

**Comment by rossberg** [comment]
Okay, interpreter now succeeding as well!

**Review by f52985 — APPROVED** [review]

**Comment by rossberg** [comment]
Turns out the interpreter isn't quite done yet. After adding a few more missing rules for bubbling branches and exceptions, it now fails again.

The issue is that the addition of handlers adds a new form of context (analogous to frames and labels), which apparently requires some deeper changes to the prose generator and interpreter. I had a look, but I am not confident enough with the code to make those particular additions myself. @f52985, could you or somebody else have a look into that?

Which made me wonder why the tests succeeded earlier. How do the test runs for the interpreter work? Are the test directories one-time just copies of the actual spec tests? That would be very bad, because then they don't get updated automatically, and we are missing quite a few tests already. Can we change the infrastructure so that these test suites are auto-updated from the original sources (at least for Wasm 3.0)?

**Comment by f52985** [comment]
> The issue is that the addition of handlers adds a new form of context (analogous to frames and labels), which apparently requires some deeper changes to the prose generator and interpreter. I had a look, but I am not confident enough with the code to make those particular additions myself. @f52985, could you or somebody else have a look into that?

Yes, we'll look into in.

> Can we change the infrastructure so that these test suites are auto-updated from the original sources (at least for Wasm 3.0)?

Yes, updating the infrastructure is fairly simple: we can just set `spec-test-3` as the symbolic link to the official test directory, which seems to work pretty well. I will update the test directory structure after handling the new test-failures coming from the new tests.

**Comment by f52985** [comment]
Here's a short update about the progress:

Supporting the new context `HANDLER_` was relatively straightforward, since we designed the translation of contexts in mind with the extensibility. And I also did some refactoring so that the context handling becomes more generalized and readable.

The problem though, is the translation of the reduction rules for the wasm instruction `THROW_REF`, for several reasons:
1) The rules violate one of our assumptions of porse translation: ALL left-hand-sides of the reduction rules are, EITHER "in-context" (i.e. reduction rules for `BR` or `RETURN`), or "out-context" (i.e. most other rules) . But for `THROW_REF`, in contains BOTH kinds of rules: `Step_read/throw_ref-null` is "out-context" while other rules are "in-context". This violation of assumption breaks the current translation and we have to make a major change for the translation process, which might take a while.
2) It seems merely impossible to generate the prose for "uncaught-exception" case (i.e. `Return the exception (ref.exn a)
 as a result.`), purely based on the reduction rules, since this corresponds to the case where "no formal reduction rule can be applied". At least some amount of hardcode might be required for this. I'll try not to make it too ad-hoc, but in the worst case, it might end up something like `if name = "THROW_REF" then insert_return_exc_instr ()`...

**Comment by rossberg** [comment]
Thanks for tackling this. I can see why (1) is a problem. Not sure I fully understand (2). Is there a specific rule for which this comes up?

**Comment by f52985** [comment]
(2) is also related to rule for `THROW_REF`.

Here's the official prose for the execution semantics of `THROW_REF`:
스크린샷 2024-08-08 오후 5 42 44

On line 12-a, there is the instruction:
`Return the exception (ref.exn a) as a result.`

which.. comes out of nowhere.

None of the formal reduction rules explicitly states that, "the result is exception",
and instead, the prose "the result is exception" corresponds to the case where none of the reduction rules are applied (especially in the case where the `THROW_REF` instruction is not in a `HANDLER_` context), and the evaluation gets stuck.

**Comment by rossberg** [comment]
Ah, yes. That prose admittedly is a bit hand-wavy. With this proposal, the definition of result is extended to include exceptions, so this kind of asserts we're done. But I'm not tied to the specific wording. Could there be a better way to express this?

**Comment by f52985** [comment]
Here's the update:

1) We did the refactorings on the il2al translation to handle the case where both in-context and out-context rules are used, which also happens to improve the overall structure of the translation too! It also revealed some of the typos in the existing auxilirary function `$allocdata`, which is a good sign.

2) Then we fixed our translation so that all new tests (`throw.wast`, `throw_ref.wast`, `try_table.wast`) are now passing! Most of test failures were due to the violated assumptions we made on the reduction rule (especially regarding the use of context), and generalizing the translation process made it possible to pass the test. Also, there was an error in the reduction rule for the instruction `THROW` which is fixed by now, so please take a look and see if the revised rule looks good.

3) There are still a few problems to be solved though.
* First, we do not support "Uncaught exception as a result" yet. (As mentioned in the previous comment). When I said all tests are passing before, that actually excluded the new kinds of assertions in .wast, namely `assert_exception`s. So what we need is (1) the hardcoded-prose for explicitly stating the "returning the exception as a result", and (2) implement new features for tester to support the `assert_exception`.
* Second, the prose for the reduction rule for `THROW_REF` is a bit redundant, due to the last "otherwise" case. Since "Otherwise" is appended as the negation of all previous if statements, and there are plenty of them some of which are nested, resulting in the duplicated proses. (This is also somewhat related to "If to Assertion" problem.)
* Still, I think is a good time to merge this PR into the main branch to prevent the further deviation with main branch, since the current version is functional in a sense that it can at least pass all "normal" tests. I believe any further changes could be worked on the main branch.

**Comment by rossberg** [comment]
Excellent, thank you @f52985! Please feel free to merge, I agree this is a good time to do that.

**Comment by f52985** [comment]
For anyone who reached here after facing the build failure:

Please make sure that you run
```sh
make distclean
```
which will remove the outdated copy of `reference_interpreter` directory.

**Pull request merged**
