### PR TITLE
Use symbolic link for spec-test-3

### PR DESCRIPTION
**Pull request by f52985**
This PR sets symbolic link for `spec-test-3` directory to the official Wasm test suite so that the test-suite is always in sync,
and it also includes some tweaks, so that the new tests can be passed.

---

There's still an issue though:
A new test case in `global.wast:373` contains the incrementally built globals:
```wasm
(module
  (global i32 (i32.const 0))
  (global i32 (global.get 0))
)
```
and since the spec does not support the incremental globals yet, it is impossible to pass this test for now.

I think I can either leave this PR open until the incremental global is supported,
or merge it now with explicitly promoting the the expected result of `dune test test-interpreter` as "non-100% pass rate".

@rossberg, what do you prefer?

### CODE REVIEW

**Comment by rossberg** [comment]
Thanks, @f52985! Just leave the PR open for now, I'll try to fix it today.

**Comment by rossberg** [comment]
I implemented incremental initialisation of globals, see commit. But unfortunately, I now get another "key not in map" error, although in this case, I don't think there is any circularity.

If we can get this to work, it should be enough as a first fix.

Mid-term I'd like to refactor the specification of instantiation to proper inductive reduction. See an initial attempt [here](https://github.com/Wasm-DSL/spectec/compare/test...Wasm-DSL:spectec:inst?expand=1). This generally is more elegant, but there are two hurdles:

1. It's a new reduction relation that requires support from the algorithmic backends.
2. The way it constructs mutual recursive functions via an administrative fix operator creates temporary states in which the store isn't well-formed according to our current semantics (a function may contain forward references that are not yet in its closure). To enable soundness, it looks like we'll need some form of type state to track which function instances are "complete" already. This is related to discussions about refactoring instantiation that @conrad-watt and I had before. I don't quite know yet how to solve this more elegantly.

**Comment by f52985** [comment]
**1) Solved issue**

> I now get another "key not in map" error, although in this case

The main problem was that the prose for `$evalglobals` had a free variable `z`, denoting the state.

Overall, the prose follows the convention that the store `s` and the frame `f` are implicitly defined,
so during the translation from IL to AL, some complicated steps are required to handle the use of frame, stores, and state variables.
This kinda did not work well for the new function `$evalglobals`, leaving the variable `z` as a free identifier in the prose as a result.
We fixed the translation so that the handling of these variables can be handled in more robust and uniform ways.

---

**2) New issue**

As a result, it seems that the generated prose looks correct now.
However, it resulted in a test failure again for this testcase:
```wast
(module
  (global $g0 (import "G" "g") i32)
  (global $g1 i32 (i32.const 8))
  (global $g2 i32 (global.get $g0))
  (global $g3 i32 (global.get $g1))

  (global $gf funcref (ref.func $f))
  (func $f)

  (table $t 10 funcref (ref.null func))
  (elem (table $t) (global.get $g2) funcref (ref.func $f))
  (elem (table $t) (global.get $g3) funcref (global.get $gf))

  (memory $m 1)
  (data (global.get $g2) "\44\44\44\44")
  (data (global.get $g3) "\88\88\88\88")

  (func (export "get-elem") (param $i i32) (result funcref)
    (table.get $t (local.get $i))
  )
  (func (export "get-data") (param $i i32) (result i32)
    (i32.load (local.get $i))
  )
)
```

The problem seems to be the second elem which evaluates the `global.get $gf`,
which is still not supported by the modified spec, because evaluating elem still uses the original state `z`:
```
  -- (Eval_expr : z; expr_E ~>* z; ref_E)**
```
So it seems that some change to the spec would be required again.

---

**3) New style for instantiation**

> Mid-term I'd like to refactor the specification of instantiation to proper inductive reduction.

I had a look and and it looks much better and simpler!

> It's a new reduction relation that requires support from the algorithmic backends.

I believe we can make the algorithmic backends support the new kind of instantiation rule (although it may require some time and effort)

**Comment by rossberg** [comment]
Oops, yes, (2) was an oversight on my part. Should be fixed now by threading back the final z. But I now get this error:
```
+9-module.watsup:181.19-181.21: interpreter error: $instantiate: on expr `the activation of z'` inner expr is not a frame (interpreting 1. Push the activation of z' to the stack.)
```

**Comment by f52985** [comment]
> But I now get this error:

The error is again, related to the state variables (`z`).

Fixed it, and all new tests are passing now!

I think we might need some more refactorings for more robust handling of state variables,
or/and handling the new style of instantiation,

yet since this the purpose of this PR is enabling the use of up-to-date official wasm 3 tests
which is achieved by now,
I think this is a good time to close this PR.

**Pull request merged**
