### PR TITLE
Make float ops nondeterministic

### PR DESCRIPTION
**Pull request by rossberg**
This PR changes all numeric ops that return floats to return lists of values, in order to model their non-determinism accurately.

That requires changing reduction rule side conditions of the form `if c = ...` to `if c <- ...`. However, the prose/interpreter backends do not know about this form of binding yet, and probably need non-trivial extensions to handle it.

@f52985, @ShinWonho, can I pass this to you?

### CODE REVIEW

**Comment by f52985** [comment]
It seems it's works well now!
Here's a brief list of important changes:

* Prose backend
AL now has new expression `ChooseE e`, which is rendered as "an element of e". (i.e. "Let c be an element of $unop(nt, unop, c_1)").

* Interpreter backend
The non-deterministic hard-coded numeric functions (in `backend-prose/numerics.ml`) are changed so that they now return a list of values.

* Middlend
The `sidecondition` pass also injects the sidecondition `--if |e2| > 0` for the IL expression `MemE(e1, e2)`, which helps an easy generation of prose.

* Spec
  - Other non-deterministic functions other than float, such as `div`, `rem`, or `trunc`, also returns a list of values.
  - Changes are also applied to wasm 1.0 and 2.0.
  - Here was the most tricky part: the new auxiliary function `$mapinvlanes` was a bit incorrect, and I had to implement some list-monadic-thingy with the auxiliary function named `$listproduct`, to concisely describe the exact expected behavior.

**Comment by rossberg** [comment]
Thanks @f52985!

> * Other non-deterministic functions other than float, such as `div`, `rem`, or `trunc`, also returns a list of values.

Ah, yes. They aren't actually non-deterministic, but partial. Maybe I'll try to change them into returning an optional value to make that clearer.

> * Here was the most tricky part: the new auxiliary function `$mapinvlanes` was a bit incorrect, and I had to implement some list-monadic-thingy with the auxiliary function named `$listproduct`, to concisely describe the exact expected behavior.

Indeed, that was nonsense. Thanks for fixing!

**Comment by rossberg** [comment]
@f52985, I turned the partial functions into option-returning ones. For that I needed a small helper:
```
def $list_(syntax X, X?) : X*  hint(show %2)
def $list_(syntax X, eps) = eps
def $list_(syntax X, w) = w
```
But something goes wrong, as I get this error:
```
../../test-interpreter/spec-test-3/conversions.wast:64.1-64.73
: interpreter error: list_: unwrap_optv: [0x0] (interpreting IfI (
  UnE (notDefinedE (IterE (VarE (X_u0), [X_u0], ?)))
then
  ReturnI (ListE ([]))
else
))
```
The presence of the UnE seems wrong to me. Could this be a bug in IL2AL?

**Comment by rossberg** [comment]
Never mind, that was merely a bug in the AL pretty printer. I fixed that and found the real issue. Now working.

**Pull request merged**
